<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PcBuilder.Domain\PcBuilder.Domain.csproj" />
      <ProjectReference Include="..\PcBuilder.Infrastructure\PcBuilder.Infrastructure.csproj" />
    </ItemGroup>

</Project>
